In [1]:
from abnumber import Chain
import pandas as pd
import numpy as np

In [27]:
chen_data = pd.read_csv("data/chen_data.csv", sep=";")
chen_data

,Antibody_ID,heavy,light,Y
0,12e8,EVQLQQSGAEVVRSGASVKLSCTASGFNIKDYYIHWVKQRPEKGLE...,DIVMTQSQKFMSTSVGDRVSITCKASQNVGTAVAWYQQKPGQSPKL...,0
1,15c8,EVQLQQSGAELVKPGASVKLSCTASGFNIKDTYMHWVKQKPEQGLE...,DIVLTQSPAIMSASLGERVTMTCTASSSVSSSNLHWYQQKPGSSPK...,0
2,1a0q,EVQLQESDAELVKPGASVKISCKASGYTFTDHVIHWVKQKPEQGLE...,DIELTQSPSSLSASLGGKVTITCKASQDIKKYIGWYQHKPGKQPRL...,1
3,1a14,QVQLQQSGAELVKPGASVRMSCKASGYTFTNYNMYWVKQSPGQGLE...,DIELTQTTSSLSASLGDRVTISCRASQDISNYLNWYQQNPDGTVKL...,0
4,1a2y,QVQLQESGPGLVAPSQSLSITCTVSGFSLTGYGVNWVRQPPGKGLE...,DIVLTQSPASLSASVGETVTITCRASGNIHNYLAWYQQKQGKSPQL...,0
...,...,...,...,...
2404,6s5a,EVKLLESGGGLVQPGGSLKLSCAASGFDFSRYWMNWVRQAPGKGLE...,QAVVTQESALTTSPGETVTLTCRSSTGAVTTSNYANWVQEKPDHLF...,0
2405,6tyb,EVQLVQSGTEVKRPGESLTISCKTSGYSFSGTWISWVRQMPGKGLE...,DIQMTQSPSSLSASVGDRVTITCRASQGISTYLAWYQQKPGKAPKL...,0
2406,6u1t,EVQLVESGGGLVKPGGSLKLSCAASGFTFSSYDMSWVRQTPEKRLE...,DIQMTQSPASQSASLGESVTITCLASQTIGTWLAWYQQKPGKSPQL...,0
2407,7fab,AVQLEQSGPGLVRPSQTLSLTCTVSGTSFDDYYWTWVRQPPGRGLE...,ASVLTQPPSVSGAPGQRVTISCTGSSSNIGAGHNVKWYQQLPGTAP...,0
2408,8fab,AVKLVQAGGGVVQPGRSLRLSCIASGFTFSNYGMHWVRQAPGKGLE...,SYELTQPPSVSVSPGQTARITCSANALPNQYAYWYQQKPGRAPVMV...,0

In [7]:
def split_ab(row):
    ab_seq = row["Antibody"]
    h, l = ab_seq.split(",")
    h = "".join(filter(str.isalnum, h))
    l = "".join(filter(str.isalnum, l))
    return h, l

In [24]:
chains_df = chen_data.apply(split_ab, axis=1, result_type="expand")
chen_data["heavy"] = chains_df[0]
chen_data["light"] = chains_df[1]
chen_data.drop("Antibody", axis=1)

,Antibody_ID,Y,heavy,light
0,12e8,0,EVQLQQSGAEVVRSGASVKLSCTASGFNIKDYYIHWVKQRPEKGLE...,DIVMTQSQKFMSTSVGDRVSITCKASQNVGTAVAWYQQKPGQSPKL...
1,15c8,0,EVQLQQSGAELVKPGASVKLSCTASGFNIKDTYMHWVKQKPEQGLE...,DIVLTQSPAIMSASLGERVTMTCTASSSVSSSNLHWYQQKPGSSPK...
2,1a0q,1,EVQLQESDAELVKPGASVKISCKASGYTFTDHVIHWVKQKPEQGLE...,DIELTQSPSSLSASLGGKVTITCKASQDIKKYIGWYQHKPGKQPRL...
3,1a14,0,QVQLQQSGAELVKPGASVRMSCKASGYTFTNYNMYWVKQSPGQGLE...,DIELTQTTSSLSASLGDRVTISCRASQDISNYLNWYQQNPDGTVKL...
4,1a2y,0,QVQLQESGPGLVAPSQSLSITCTVSGFSLTGYGVNWVRQPPGKGLE...,DIVLTQSPASLSASVGETVTITCRASGNIHNYLAWYQQKQGKSPQL...
...,...,...,...,...
2404,6s5a,0,EVKLLESGGGLVQPGGSLKLSCAASGFDFSRYWMNWVRQAPGKGLE...,QAVVTQESALTTSPGETVTLTCRSSTGAVTTSNYANWVQEKPDHLF...
2405,6tyb,0,EVQLVQSGTEVKRPGESLTISCKTSGYSFSGTWISWVRQMPGKGLE...,DIQMTQSPSSLSASVGDRVTITCRASQGISTYLAWYQQKPGKAPKL...
2406,6u1t,0,EVQLVESGGGLVKPGGSLKLSCAASGFTFSSYDMSWVRQTPEKRLE...,DIQMTQSPASQSASLGESVTITCLASQTIGTWLAWYQQKPGKSPQL...
2407,7fab,0,AVQLEQSGPGLVRPSQTLSLTCTVSGTSFDDYYWTWVRQPPGRGLE...,ASVLTQPPSVSGAPGQRVTISCTGSSSNIGAGHNVKWYQQLPGTAP...
2408,8fab,0,AVKLVQAGGGVVQPGRSLRLSCIASGFTFSNYGMHWVRQAPGKGLE...,SYELTQPPSVSVSPGQTARITCSANALPNQYAYWYQQKPGRAPVMV...

In [28]:
chain = Chain(chen_data.iloc[1]["heavy"], scheme='imgt')
chain

EVQLQQSGAELVKPGASVKLSCTASGFNIKDTYMHWVKQKPEQGLEWIAQIDPANGNTKYDPKFQGKATITADTSSNTAYLHLSSLTSEDSAVYYCAADPPYYGHGDYWGQGTTLTVSS
                         ^^^^^^^^                 ^^^^^^^^                                      ^^^^^^^^^^^^

In [32]:
def chainify(seq):
    try:
        ch = Chain(seq, scheme="imgt")
        return ch
    except NotImplementedError as e:
        return None

In [33]:
heavy = [chainify(h_seq) for h_seq in chen_data["heavy"]]
light = [chainify(l_seq) for l_seq in chen_data["light"]]
len(heavy)

2409

In [45]:
heavy_mask = [ch is not None for ch in heavy]
light_mask = [ch is not None for ch in light]
heavy_mask[:10]

[True, True, True, True, True, True, True, True, True, True]

In [55]:
heavy_ids = chen_data["Antibody_ID"][heavy_mask]
light_ids = chen_data["Antibody_ID"][light_mask]

In [49]:
heavy_clean = [ch for ch in heavy if ch is not None]
light_clean = [ch for ch in light if ch is not None]

In [58]:
heavy_df = Chain.to_dataframe(heavy_clean)
heavy_df.insert(0, "Ab_ID", heavy_ids)
heavy_df

/home/brazdilv/.conda/envs/ab/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3364: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  if (await self.run_code(code, result,  async_=asy)):

,Ab_ID,chain_type,species,1,2,3,3A,4,4A,5,...,119,120,121,122,123,124,125,126,127,128
Id,,,,,,,,,,,,,,,,,,,,,
0,12e8,H,mouse,E,V,Q,-,L,-,Q,...,G,Q,G,T,L,V,T,V,S,A
1,15c8,H,mouse,E,V,Q,-,L,-,Q,...,G,Q,G,T,T,L,T,V,S,S
2,1a0q,H,mouse,E,V,Q,-,L,-,Q,...,G,Q,G,T,T,L,T,V,S,S
3,1a14,H,mouse,Q,V,Q,-,L,-,Q,...,G,Q,G,T,T,V,T,V,-,-
4,1a2y,H,mouse,Q,V,Q,-,L,-,Q,...,G,Q,G,T,T,L,T,V,S,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2402,6rcq,H,alpaca,E,V,K,-,L,-,L,...,G,Q,G,T,L,V,T,V,S,A
2403,6rcs,H,human,E,V,Q,-,L,-,V,...,G,Q,G,A,L,V,T,V,S,S
2404,6s5a,H,alpaca,E,V,Q,-,L,-,V,...,G,Q,G,T,L,V,T,V,S,A
2405,6tyb,H,human,A,V,Q,-,L,-,E,...,G,Q,G,S,L,V,T,V,S,S
2406,6u1t,H,alpaca,A,V,K,-,L,-,V,...,G,Q,G,V,L,V,T,V,S,S

In [59]:
light_df = Chain.to_dataframe(light_clean)
light_df.insert(0, "Ab_ID", light_ids)
light_df

/home/brazdilv/.conda/envs/ab/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3364: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  if (await self.run_code(code, result,  async_=asy)):

,Ab_ID,chain_type,species,1,2,3,4,5,6,7,...,118,119,120,121,122,123,124,125,126,127
Id,,,,,,,,,,,,,,,,,,,,,
0,12e8,K,mouse,D,I,V,M,T,Q,S,...,F,G,A,G,T,K,L,E,L,K
1,15c8,K,mouse,D,I,V,L,T,Q,S,...,F,G,G,G,T,K,L,E,I,K
2,1a0q,K,rat,D,I,E,L,T,Q,S,...,F,G,G,G,T,K,L,E,I,K
3,1a14,K,mouse,D,I,E,L,T,Q,T,...,F,G,G,G,T,-,-,-,-,-
4,1a2y,K,mouse,D,I,V,L,T,Q,S,...,F,G,G,G,T,K,L,E,I,K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2404,6s5a,L,mouse,Q,A,V,V,T,Q,E,...,F,G,G,G,T,K,L,T,V,L
2405,6tyb,K,rhesus,D,I,Q,M,T,Q,S,...,F,G,Q,G,T,K,V,E,I,K
2406,6u1t,K,mouse,D,I,Q,M,T,Q,S,...,F,G,G,G,T,K,L,E,I,K
2407,7fab,L,rhesus,A,S,V,L,T,Q,P,...,F,G,G,G,T,K,L,T,V,L
2408,8fab,L,human,S,Y,E,L,T,Q,P,...,F,G,G,G,T,K,L,T,V,L

In [60]:
heavy_df.to_csv("data/chen_heavy_chain_numbering.csv", index=False)
light_df.to_csv("data/chen_light_chain_numbering.csv", index=False)

In [92]:
AAs = "ACDEFGHIKLMNOPQRSTUVWY-"
aa_to_int = dict((c, i) for i, c in enumerate(AAs))

In [108]:
def one_hot_encode_protein(seq):
    int_seq = [aa_to_int[aa] for aa in seq]
    onehot_encoded = []
    for val in int_seq:
        vect = [0 for i in range(len(AAs) - 1)]
        if val != 22:
            vect[val] = 1
        onehot_encoded += vect
    return np.asarray(onehot_encoded)

In [106]:
def encode_proteins(data):
    res = data.apply(one_hot_encode_protein, axis=1, result_type="expand")
    return res

In [ ]:
def get_col_names(n):
    names = []
    for i in range(n):
        letters = [f"{ch}_{i + 1}" for ch in "ACDEFGHIKLMNOPQRSTUVWY"]
        names += letters
    return names

In [109]:
encode_proteins(heavy_df.iloc[2:5,3:])

,0,1,2,3,4,5,6,7,8,9,...,4478,4479,4480,4481,4482,4483,4484,4485,4486,4487
Id,,,,,,,,,,,,,,,,,,,,,
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [124]:
heavy_one_hot = encode_proteins(heavy_df.iloc[:,3:])
heavy_one_hot.insert(0, "Ab_ID", heavy_df["Ab_ID"])
heavy_one_hot.columns = ["Ab_ID"] + get_col_names(len(heavy_df.columns) - 3)
heavy_one_hot.reset_index().to_feather("data/chen_heavy_one_hot.ftr")

In [126]:
light_one_hot = encode_proteins(light_df.iloc[:,3:])
light_one_hot.insert(0, "Ab_ID", light_df["Ab_ID"])
light_one_hot.columns = ["Ab_ID"] + get_col_names(len(light_df.columns) - 3)
light_one_hot.reset_index().to_feather("data/chen_light_one_hot.ftr")